const video = [
	{
		id: 1,
		title: "Wrath Of Man",
		category: "action",
		rating: "7,08",
		year: 2021,
		img: "./watch-best-movie/images/Movies/wrath-of-man.jpg",
		desc: "The plot follows H, a cold and mysterious character working at a cash truck company responsible for moving hundreds of millions of dollars around Los Angeles each week.",
		href: "https://youtu.be/EFYEni2gsK0",
	},
	{
		id: 2,
		title: "Joker",
		category: "drama",
		rating: "8,32",
		year: 2019,
		img: "./watch-best-movie/images/Movies/joker.jpg",
		desc: "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
		href: "https://www.youtube.com/watch?v=t433PEQGErc",
	},
	{
		id: 3,
		title: "Gran Torino",
		category: "drama",
		rating: "8,28",
		year: 2008,
		img: "./watch-best-movie/images/Movies/gran-torino.jpg",
		desc: "Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, Thao Lor, a Hmong teenager who tried to steal Kowalski's prized possession: a 1972 Gran Torino.",
		href: "https://www.youtube.com/watch?v=RMhbr2XQblk",
	},
	{
		id: 4,
		title: "Green book",
		category: "drama",
		rating: "8,21",
		year: 2008,
		img: "./watch-best-movie/images/Movies/green-book.jpg",
		desc: "A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour of venues through the 1960s American South.",
		href: "https://www.youtube.com/watch?v=QkZxoko_HC0",
	},
	{
		id: 5,
		title: "Gladiator",
		category: "drama",
		rating: "8,19",
		year: 2000,
		img: "./watch-best-movie/images/Movies/gladiator.jpg",
		desc: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
		href: "https://www.youtube.com/watch?v=owK1qxDselE",
	},
	{
		id: 6,
		title: "John Wick",
		category: "action",
		rating: "6,99",
		year: 2014,
		img: "./watch-best-movie/images/Movies/john-wick.jpg",
		desc: "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
		href: "https://www.youtube.com/watch?v=2AUmvWm5ZDQ",
	},
	{
		id: 7,
		title: "The Green Mile",
		category: "drama",
		rating: "8,63",
		year: 1999,
		img: "./watch-best-movie/images/Movies/green-mile.jpg",
		desc: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
		href: "https://www.youtube.com/watch?v=Ki4haFrqSrw",
	},
	{
		id: 8,
		title: "Nobody",
		category: "action",
		rating: "7,23",
		year: 2021,
		img: "./watch-best-movie/images/Movies/nobody.jpg",
		desc: "A docile family man slowly reveals his true character after his house gets burgled by two petty thieves, which, coincidentally, leads him into a bloody war with a Russian crime boss.",
		href: "https://www.youtube.com/watch?v=wZti8QKBWPo",
	},
	{
		id: 9,
		title: "The Bourne Identify",
		category: "action",
		rating: "7,65",
		year: 2002,
		img: "./watch-best-movie/images/Movies/bourne.jpg",
		desc: "A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and attempting to regain his memory.",
		href: "https://www.youtube.com/watch?v=FpKaB5dvQ4g",
	},
	{
		id: 10,
		title: "Taken",
		category: "action",
		rating: "7,61",
		year: 2008,
		img: "./watch-best-movie/images/Movies/taken.jpg",
		desc: "A retired CIA agent travels across Europe and relies on his old skills to save his estranged daughter, who has been kidnapped while on a trip to Paris.",
		href: "https://www.youtube.com/watch?v=uPJVJBm9TPA",
	},
	{
		id: 11,
		title: "Intouchables",
		category: "comedy",
		rating: "8,65",
		year: 2011,
		img: "./watch-best-movie/images/Movies/intouchables.jpg",
		desc: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
		href: "https://www.youtube.com/watch?v=34WIbmXkewU",
	},
	{
		id: 12,
		title: "Ted",
		category: "comedy",
		rating: "6,93",
		year: 2012,
		img: "./watch-best-movie/images/Movies/ted.jpg",
		desc: "John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear, Ted or his girlfriend, Lori.",
		href: "https://www.youtube.com/watch?v=9fbo_pQvU7M",
	},
	{
		id: 13,
		title: "Airplane II: The Sequel",
		category: "comedy",
		rating: "6,98",
		year: 1982,
		img: "./watch-best-movie/images/Movies/airplane.jpg",
		desc: "A faulty computer causes a passenger space shuttle to head straight for the Sun. Can Ted Striker save the day and get the shuttle back on track - again?",
		href: "https://www.youtube.com/watch?v=yk2qQNME5x4",
	},
	{
		id: 14,
		title: "Meet the Fockers",
		category: "comedy",
		rating: "6,77",
		year: 2004,
		img: "./watch-best-movie/images/Movies/meet-the-fockers.jpg",
		desc: "All hell breaks loose when the Byrnes family meets the Focker family for the first time.",
		href: "https://www.youtube.com/watch?v=r5Vpw5QP8FU",
	},
	{
		id: 15,
		title: "Monty Python and the Holy Grail",
		category: "comedy",
		rating: "8,27",
		year: 1975,
		img: "./watch-best-movie/images/Movies/monty-python.jpg",
		desc: "King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail, encountering many, very silly obstacles.",
		href: "https://www.youtube.com/watch?v=urRkGvhXc8w",
	},
	{
		id: 16,
		title: "The Curious Case of Benjamin Button",
		category: "romance",
		rating: "7,77",
		year: 2008,
		img: "./watch-best-movie/images/Movies/Benjamin.jpg",
		desc: "Tells the story of Benjamin Button, a man who starts aging backwards with consequences.",
		href: "https://www.youtube.com/watch?v=iH6FdW39Hag",
	},
	{
		id: 17,
		title: "Joe Black",
		category: "romance",
		rating: "7,62",
		year: 1998,
		img: "./watch-best-movie/images/Movies/joe-black.jpg",
		desc: "Death, who takes the form of a young man, asks a media mogul to act as a guide to teach him about life on Earth, and in the process, he falls in love with his guide's daughter.",
		href: "https://www.youtube.com/watch?v=_zIOjl93WrU",
	},
	{
		id: 18,
		title: "Gone with the Wind",
		category: "romance",
		rating: "8,25",
		year: 1939,
		img: "./watch-best-movie/images/Movies/gone-with-the-wind.jpg",
		desc: "The manipulative daughter of a Georgia plantation owner conducts a turbulent romance with a roguish profiteer during the American Civil War and Reconstruction periods.",
		href: "https://www.youtube.com/watch?v=0X94oZgJis4",
	},
	{
		id: 19,
		title: "The Notebook",
		category: "romance",
		rating: "8,02",
		year: 2004,
		img: "./watch-best-movie/images/Movies/notebook.jpg",
		desc: "A poor yet passionate young man (Ryan Gosling) falls in love with a rich young woman (Rachel McAdams), giving her a sense of freedom, but they are soon separated because of their social differences.",
		href: "https://www.youtube.com/watch?v=FC6biTjEyZw",
	},
	{
		id: 20,
		title: "A Star is Born",
		category: "romance",
		rating: "7,63",
		year: 2018,
		img: "./watch-best-movie/images/Movies/star-is-born.jpg",
		desc: "A musician helps a young singer find fame as age and alcoholism send his own career into a downward spiral.",
		href: "https://www.youtube.com/watch?v=nSbzyEJ8X9E",
	},
	{
		id: 21,
		title: "The Shining",
		category: "horror",
		rating: "8,36",
		year: 1980,
		img: "./watch-best-movie/images/Movies/the-shining.jpg",
		desc: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
		href: "https://www.youtube.com/watch?v=5Cb3ik6zP2I",
	},
	{
		id: 22,
		title: "The Thing",
		category: "horror",
		rating: "8,15",
		year: 1982,
		img: "./watch-best-movie/images/Movies/the-thing.jpg",
		desc: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
		href: "https://www.youtube.com/watch?v=5ftmr17M-a4",
	},
	{
		id: 23,
		title: "Sleepy Hollow",
		category: "horror",
		rating: "7,59",
		year: 1999,
		img: "./watch-best-movie/images/Movies/sleepy-hollow.jpg",
		desc: "Ichabod Crane is sent to Sleepy Hollow to investigate the decapitations of three people, with the culprit being the legendary apparition, The Headless Horseman.",
		href: "https://www.youtube.com/watch?v=6RsKwn_Je1k",
	},
	{
		id: 24,
		title: "The Conjuring",
		category: "horror",
		rating: "7,43",
		year: 2013,
		img: "./watch-best-movie/images/Movies/the-conjuring.jpg",
		desc: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
		href: "https://www.youtube.com/watch?v=k10ETZ41q5o",
	},
	{
		id: 25,
		title: "The Ring",
		category: "horror",
		rating: "6,91",
		year: 2002,
		img: "./watch-best-movie/images/Movies/the-ring.jpg",
		desc: "A journalist must investigate a mysterious videotape which seems to cause the death of anyone one week to the day after they view it.",
		href: "https://www.youtube.com/watch?v=yzR2GY-ew8I",
	},
	{
		id: 26,
		title: "The Lord of the Rings",
		category: "fantasy",
		rating: "8,85",
		year: 2001,
		img: "./watch-best-movie/images/Movies/the-lotr.jpg",
		desc: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
		href: "https://www.youtube.com/watch?v=V75dMMIW2B4",
	},
	{
		id: 27,
		title: "The Hobbit: An Unexpected Journey",
		category: "fantasy",
		rating: "7,95",
		year: 2012,
		img: "./watch-best-movie/images/Movies/hobbit.jpg",
		desc: "A reluctant Hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home, and the gold within it from the dragon Smaug.",
		href: "https://www.youtube.com/watch?v=SDnYMbYB-nU",
	},
	{
		id: 28,
		title: "Constantine",
		category: "fantasy",
		rating: "7,33",
		year: 2005,
		img: "./watch-best-movie/images/Movies/constantine.jpg",
		desc: "Supernatural exorcist and demonologist John Constantine helps a policewoman prove her sister's death was not a suicide, but something more.",
		href: "https://www.youtube.com/watch?v=DEa508Xmmio",
	},
	{
		id: 29,
		title: "Pirates of the Caribbean",
		category: "fantasy",
		rating: "8,00",
		year: 2003,
		img: "./watch-best-movie/images/Movies/pirates.jpg",
		desc: `Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.`,
		href: "https://www.youtube.com/watch?v=naQr0uTrH_s",
	},
	{
		id: 30,
		title: "300",
		category: "fantasy",
		rating: "7,46",
		year: 2006,
		img: "./watch-best-movie/images/Movies/300.jpg",
		desc: "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
		href: "https://www.youtube.com/watch?v=UrIbxk7idYA",
	},
	{
		id: 31,
		title: "Se7en",
		category: "thriller",
		rating: "8,86",
		year: 1995,
		img: "./watch-best-movie/images/Movies/seven.jpg",
		desc: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
		href: "https://www.youtube.com/watch?v=znmZoVkCjpI",
	},
	{
		id: 32,
		title: "Fight Club",
		category: "thriller",
		rating: "8,68",
		year: 1999,
		img: "./watch-best-movie/images/Movies/fight-club.jpg",
		desc: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
		href: "https://www.youtube.com/watch?v=qtRKdVHc-cE",
	},
	{
		id: 33,
		title: "The Silence of the Lambs",
		category: "thriller",
		rating: "8,52",
		year: 1991,
		img: "./watch-best-movie/images/Movies/lambs.jpg",
		desc: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
		href: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
	},
	{
		id: 34,
		title: "Prisoners",
		category: "thriller",
		rating: "8,14",
		year: 2013,
		img: "./watch-best-movie/images/Movies/prisoners.jpg",
		desc: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
		href: "https://www.youtube.com/watch?v=bpXfcTF6iVk",
	},
	{
		id: 35,
		title: "Law Abiding Citizen",
		category: "thriller",
		rating: "7,81",
		year: 2009,
		img: "./watch-best-movie/images/Movies/law-abiding-citizen.jpg",
		desc: "A frustrated man decides to take justice into his own hands after a plea bargain sets one of his family's killers free.",
		href: "https://www.youtube.com/watch?v=LX6kVRsdXW4",
	},
	{
		id: 36,
		title: "Django Unchained",
		category: "western",
		rating: "8,55",
		year: 2012,
		img: "./watch-best-movie/images/Movies/django.jpg",
		desc: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.",
		href: "https://www.youtube.com/watch?v=0fUCuvNlOCg",
	},
	{
		id: 37,
		title: "Good, bad, ugly",
		category: "western",
		rating: "8,81",
		year: 1966,
		img: "./watch-best-movie/images/Movies/good-bad-ugly.jpg",
		desc: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
		href: "https://www.youtube.com/watch?v=WCN5JJY_wiA",
	},
	{
		id: 38,
		title: "Once upon a time in the west",
		category: "western",
		rating: "8,59",
		year: 1968,
		img: "./watch-best-movie/images/Movies/once-upon-a-time.jpg",
		desc: "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.",
		href: "https://www.youtube.com/watch?v=c8CJ6L0I6W8",
	},
	{
		id: 39,
		title: "Unforgiven",
		category: "western",
		rating: "8,27",
		year: 1992,
		img: "./watch-best-movie/images/Movies/unforgiven.jpg",
		desc: `Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man, The "Schofield Kid."`,
		href: "https://www.youtube.com/watch?v=ftTX4FoBWlE",
	},
	{
		id: 40,
		title: "Dances with Wolves",
		category: "western",
		rating: "8,02",
		year: 1990,
		img: "./watch-best-movie/images/Movies/dance-with-wolves.jpg",
		desc: "Lieutenant John Dunbar, assigned to a remote western Civil War outpost, befriends wolves and Native Americans, making him an intolerable aberration in the military.",
		href: "https://www.youtube.com/watch?v=uc8NMbrW7mI",
	},
];

export default video;
